### ISSUE TITLE
Render map onto device

### ISSUE THREAD

**Issue by kbonnici** [CSC485A-Slacker/slacker#3]
Using [insert agreed upon UI framework here],  this issue will be closed once we are able to render an interactable map onto the target device (this means we should be able to pinch to zoom, pan around the map, etc.) 

Some possible options we could end up going with are:
- [Google Maps](https://developers.google.com/maps)
- [Leaflet](https://leafletjs.com/)

**TIME ESTIMATE**: 6 hours

**Comment by skosman** [comment]
Completed in this PR: https://github.com/CSC485A-Slacker/slacker/pull/6
