### ISSUE TITLE
Add a pin to map

### ISSUE THREAD

**Issue by kbonnici** [CSC485A-Slacker/slacker#4]
Feature name: Drop a pin onto the user's map. At this point not much information is needed to be displayed upon clicking a pin (if we are pressed for time, we could think about not even having an interactable pin, just a droppable one).

Description: A map interface where one could drop pin to make slack spot.
Requires: Displaying the map with map API, implementing add pins functionality using map API, storing pin into database.
Status: Map shows.

**TIME ESTIMATE**: 12 hours

**Comment by skosman** [comment]
Frontend was done this this PR: https://github.com/CSC485A-Slacker/slacker/pull/6
And backend is currently done on the branch `dev-firestore`. 
Just need to connect the two. 
Time spent so far: 16 hours for frontend and 30 hours for backend. 
Estimated time left: 12 hours
