### ISSUE TITLE
Create Start Screen

### ISSUE THREAD

**Issue by skosman** [CSC485A-Slacker/slacker#9]
When a user enters the app, they are currently greeted by a view of the map. Instead they should see our logo and name to help improve brand image. Then once they've clicked the screen or time has passed, it moves to the map view. 

To implement this, we need to update the navigation in Router.tsx which uses React Navigation. 
Here's some documentation to help: https://reactnavigation.org/docs/navigating

There is also the current HomeView.tsx that contains the Name, Logo and catchline. This should be the starting basis of what the start/home screen should be.

**Comment by RanHuii** [comment]
The work is done in this [PR](https://github.com/CSC485A-Slacker/slacker/pull/45)
